<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ChartOfAccount;
use Illuminate\Support\Facades\DB;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // SQLite compatible foreign key handling
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }
        
        ChartOfAccount::truncate();
        
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = ON;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }

        $accounts = [
            // ASSETS (1000-1999)
            [
                'code' => '1000',
                'name' => 'Cash on Hand',
                'type' => 'asset',
                'category' => 'cash_on_hand',
                'normal_balance' => 'debit',
                'opening_balance' => 10000.00,
                'current_balance' => 10000.00,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Physical cash at office',
                'currency' => 'USD',
            ],
            [
                'code' => '1001',
                'name' => 'Petty Cash',
                'type' => 'asset',
                'category' => 'cash_on_hand',
                'normal_balance' => 'debit',
                'opening_balance' => 500.00,
                'current_balance' => 500.00,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Small cash for daily expenses',
                'currency' => 'USD',
            ],
            [
                'code' => '1100',
                'name' => 'Bank Accounts',
                'type' => 'asset',
                'category' => 'cash_in_bank',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Bank deposits',
                'currency' => 'USD',
            ],
            [
                'code' => '1200',
                'name' => 'Loan Portfolio',
                'type' => 'asset',
                'category' => 'loan_portfolio',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Loans receivable from clients',
                'currency' => 'USD',
            ],
            [
                'code' => '1201',
                'name' => 'Allowance for Loan Losses',
                'type' => 'asset',
                'category' => 'accumulated_depreciation',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Provision for bad debts',
                'currency' => 'USD',
            ],
            [
                'code' => '1300',
                'name' => 'Accounts Receivable',
                'type' => 'asset',
                'category' => 'accounts_receivable',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Other receivables',
                'currency' => 'USD',
            ],
            [
                'code' => '1400',
                'name' => 'Office Equipment',
                'type' => 'asset',
                'category' => 'property_plant_equipment',
                'normal_balance' => 'debit',
                'opening_balance' => 5000.00,
                'current_balance' => 5000.00,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Computers, furniture, etc.',
                'currency' => 'USD',
            ],
            [
                'code' => '1401',
                'name' => 'Accumulated Depreciation - Equipment',
                'type' => 'asset',
                'category' => 'accumulated_depreciation',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Depreciation on equipment',
                'currency' => 'USD',
            ],

            // LIABILITIES (2000-2999)
            [
                'code' => '2000',
                'name' => 'Client Savings',
                'type' => 'liability',
                'category' => 'client_savings',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Client deposits and savings',
                'currency' => 'USD',
            ],
            [
                'code' => '2100',
                'name' => 'Interest Payable',
                'type' => 'liability',
                'category' => 'interest_payable',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Interest owed to clients',
                'currency' => 'USD',
            ],
            [
                'code' => '2200',
                'name' => 'Accounts Payable',
                'type' => 'liability',
                'category' => 'accounts_payable',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Amounts owed to suppliers',
                'currency' => 'USD',
            ],
            [
                'code' => '2300',
                'name' => 'Bank Loans Payable',
                'type' => 'liability',
                'category' => 'loan_from_shareholders',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Loans from banks/financial institutions',
                'currency' => 'USD',
            ],

            // EQUITY (3000-3999)
            [
                'code' => '3000',
                'name' => 'Owner\'s Capital',
                'type' => 'equity',
                'category' => 'capital',
                'normal_balance' => 'credit',
                'opening_balance' => 15000.00,
                'current_balance' => 15000.00,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Initial investment',
                'currency' => 'USD',
            ],
            [
                'code' => '3100',
                'name' => 'Retained Earnings',
                'type' => 'equity',
                'category' => 'retained_earnings',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Accumulated profits',
                'currency' => 'USD',
            ],

            // REVENUE (4000-4999)
            [
                'code' => '4000',
                'name' => 'Loan Interest Income',
                'type' => 'revenue',
                'category' => 'loan_interest_income',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Interest earned on loans',
                'currency' => 'USD',
            ],
            [
                'code' => '4100',
                'name' => 'Penalty Income',
                'type' => 'revenue',
                'category' => 'penalty_income',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Late payment penalties',
                'currency' => 'USD',
            ],
            [
                'code' => '4200',
                'name' => 'Processing Fee Income',
                'type' => 'revenue',
                'category' => 'service_fees',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Loan processing fees',
                'currency' => 'USD',
            ],
            [
                'code' => '4300',
                'name' => 'System Charge Income',
                'type' => 'revenue',
                'category' => 'service_fees',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'System maintenance fees',
                'currency' => 'USD',
            ],
            [
                'code' => '4400',
                'name' => 'Other Income',
                'type' => 'revenue',
                'category' => 'other_income',
                'normal_balance' => 'credit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Miscellaneous income',
                'currency' => 'USD',
            ],

            // EXPENSES (5000-5999)
            [
                'code' => '5000',
                'name' => 'Salaries and Wages',
                'type' => 'expense',
                'category' => 'salaries_wages',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Staff salaries',
                'currency' => 'USD',
            ],
            [
                'code' => '5100',
                'name' => 'Rent Expense',
                'type' => 'expense',
                'category' => 'rent_expense',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Office rent',
                'currency' => 'USD',
            ],
            [
                'code' => '5200',
                'name' => 'Utilities Expense',
                'type' => 'expense',
                'category' => 'utilities',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Electricity, water, internet',
                'currency' => 'USD',
            ],
            [
                'code' => '5300',
                'name' => 'Office Supplies',
                'type' => 'expense',
                'category' => 'supplies',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Stationery and supplies',
                'currency' => 'USD',
            ],
            [
                'code' => '5400',
                'name' => 'Transportation Expense',
                'type' => 'expense',
                'category' => 'transportation',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Transport and fuel costs',
                'currency' => 'USD',
            ],
            [
                'code' => '5500',
                'name' => 'Marketing Expense',
                'type' => 'expense',
                'category' => 'marketing',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Advertising and promotion',
                'currency' => 'USD',
            ],
            [
                'code' => '5600',
                'name' => 'Depreciation Expense',
                'type' => 'expense',
                'category' => 'depreciation',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Asset depreciation',
                'currency' => 'USD',
            ],
            [
                'code' => '5700',
                'name' => 'Loan Loss Expense',
                'type' => 'expense',
                'category' => 'loan_loss',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => true,
                'description' => 'Bad debt write-offs',
                'currency' => 'USD',
            ],
            [
                'code' => '5800',
                'name' => 'Interest Expense',
                'type' => 'expense',
                'category' => 'interest_expense',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Interest on savings and loans',
                'currency' => 'USD',
            ],
            [
                'code' => '5900',
                'name' => 'Miscellaneous Expense',
                'type' => 'expense',
                'category' => 'miscellaneous',
                'normal_balance' => 'debit',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
                'is_system_account' => false,
                'description' => 'Other expenses',
                'currency' => 'USD',
            ],
        ];

        foreach ($accounts as $account) {
            ChartOfAccount::create($account);
        }

        $this->command->info('Chart of Accounts seeded successfully!');
    }
}
