# Fly.io Configuration for Microfinance Application
app = "microfinance-laravel"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stack"
  LOG_LEVEL = "info"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/database/database.sqlite"
  CACHE_DRIVER = "file"
  QUEUE_CONNECTION = "database"
  SESSION_DRIVER = "file"
  SESSION_LIFETIME = "120"
  BROADCAST_DRIVER = "log"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/"

